version: '3.4'
networks:
    backend:
    sql_server_network:

services:
  MS.Services.Auth.WebAPI:
    image: apiteste
    build:
      context: .
      dockerfile: ../MS.Services.Auth.WebAPI/Dockerfile
