version: '3.4'

volumes:
  mssql:
networks:
  backend:
    name: backend
  frontend:
    name: frontend
  
services:
  sqlserver:
    restart: always
    image : mcr.microsoft.com/mssql/server:2022-latest
    container_name : sqlserver
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Numsey#2021"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data
    ports:
      - 11433:1433
    networks:
      - 'backend'
    # expose:
    #   - 1433

  ms.services.auth.webapi:
    image: ms.services.auth.webapi
    container_name: ms.services.auth.webapi
    build:
      context: ./MS.Services/MS.Services.Auth/
      dockerfile: ./MS.Services.Auth.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlConnection=Server=sqlserver;Database=AuthDb;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "ConnectionStrings:SerilogSqlConnection=Server=sqlserver;Database=AppLogs;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "Logging:LogLevel:Serilog=Warning"
      - "Swagger:FlowLogin=http://localhost:4000/api/v1/auth/flowlogin"
    depends_on:
      - sqlserver
    ports:
      - '4000:80'
    networks:
      - 'backend'
      - 'frontend' 

  ms.services.courses.webapi:
    image: ms.services.courses.webapi
    container_name: ms.services.courses.webapi
    build:
      context: ./MS.Services/MS.Services.Courses/
      dockerfile: ./MS.Services.Courses.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlConnection=Server=sqlserver;Database=SchoolDb;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "ConnectionStrings:SerilogSqlConnection=Server=sqlserver;Database=AppLogs;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "Logging:LogLevel:Serilog=Warning"
      - "Swagger:FlowLogin=http://localhost:4000/api/v1/auth/flowlogin"
    depends_on:
      - sqlserver
    ports:
      - '4001:80'
    networks:
      - 'backend'

  ms.services.students.webapi:
    image: ms.services.students.webapi
    container_name: ms.services.students.webapi
    build:
      context: ./MS.Services/MS.Services.Students/
      dockerfile: ./MS.Services.Students.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlConnection=Server=sqlserver;Database=SchoolDb;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "ConnectionStrings:SerilogSqlConnection=Server=sqlserver;Database=AppLogs;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "Logging:LogLevel:Serilog=Warning"
      - "Swagger:FlowLogin=http://localhost:4000/api/v1/auth/flowlogin"
    depends_on:
      - sqlserver
    ports:
      - '4002:80'
    networks:
      - 'backend'

  ms.services.gateway.webapi:
    image: ms.services.gateway.webapi
    container_name: ms.services.gateway.webapi
    build:
      context: ./MS.Services/MS.Services.Gateway/
      dockerfile: ./MS.Services.Gateway.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlConnection=Server=sqlserver;Database=SchoolDb;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "ConnectionStrings:SerilogSqlConnection=Server=sqlserver;Database=AppLogs;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "Logging:LogLevel:Serilog=Warning"
      - "GatewayUrls:WebApiCourse=http://ms.services.courses.webapi"
      - "GatewayUrls:WebApiStudents=http://ms.services.students.webapi"
      - "Swagger:FlowLogin=http://localhost:4000/api/v1/auth/flowlogin"
    depends_on:
      - sqlserver
    ports:
      - '4003:80'
    networks:
      - 'backend'
      - 'frontend' 

  frontendms:
    image: frontendms
    container_name: frontendms
    build:
      context: ./MS.WebUI/control-services/
      dockerfile: ./Dockerfile
    ports:
      - '8080:80'
    networks:
      - 'frontend'