version: '3.4'

networks:
    backend:
    sql_server_network:

services:
  sqlserver:
    restart: always
    image : mcr.microsoft.com/mssql/server:2022-latest
    container_name : sqlserver
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Numsey#2021"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data
    ports:
      - 11433:1433
    networks:
      - sql_server_network
    expose:
      - 1433

  ms.services.auth.webapi:
    image: msservicesauthwebapi
    container_name: msservicesauthwebapi
    build:
      context: ./MS.Services/MS.Services.Auth/
      dockerfile: ./MS.Services.Auth.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlConnection=Server=sqlserver;Database=AuthDb;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
    depends_on:
      - sqlserver
    ports:
      - '4000:80'
    networks:
      - sql_server_network
      - backend

  ms.services.courses.webapi:
    image: msservicescourseswebapi
    container_name: msservicescourseswebapi
    build:
      context: ./MS.Services/MS.Services.Courses/
      dockerfile: ./MS.Services.Courses.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlConnection=Server=sqlserver;Database=SchoolDb;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "SerilogSqlConnection:Server=localhost,11433;Database=AppLogs;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "Logging:LogLevel:Serilog:Information"
    depends_on:
      - sqlserver
    ports:
      - '4001:80'
    networks:
      - sql_server_network
      - backend

  ms.services.students.webapi:
    image: msservicesstudentswebapi
    container_name: msservicesstudentswebapi
    build:
      context: ./MS.Services/MS.Services.Students/
      dockerfile: ./MS.Services.Students.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlConnection=Server=sqlserver;Database=SchoolDb;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "SerilogSqlConnection:Server=localhost,11433;Database=AppLogs;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "Logging:LogLevel:Serilog:Information"
    depends_on:
      - sqlserver
    ports:
      - '4002:80'
    networks:
      - sql_server_network
      - backend

  ms.services.gateway.webapi:
    image: msservicesgatewaywebapi
    container_name: msservicesgatewaywebapi
    build:
      context: ./MS.Services/MS.Services.Gateway/
      dockerfile: ./MS.Services.Gateway.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlConnection=Server=sqlserver;Database=SchoolDb;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "SerilogSqlConnection:Server=localhost,11433;Database=AppLogs;User Id=sa;Password=Numsey#2021;TrustServerCertificate=True;"
      - "Logging:LogLevel:Serilog:Information"
      - "GatewayUrls:WebApiCourse:https://localhost:4001"
      - "GatewayUrls:WebApiStudents:https://localhost:4002"
    depends_on:
      - sqlserver
    ports:
      - '4003:80'
    networks:
      - sql_server_network
      - backend