version: '3.4'

networks:
    backend:
    sql_server_network:

services:
  sqlserver:
    image : mcr.microsoft.com/mssql/server:2022-latest

  ms.services.auth.webapi:
    image: ${DOCKER_REGISTRY-}msservicesauthwebapi
    build:
      context: .
      dockerfile: ../MS.Services/MS.Services.Auth/MS.Services.Auth.WebAPI/Dockerfile

