version: '3.4'

networks:
    bancoMongo:

services:
  ms.services.auth.webapi:
    container_name : msservicesauthwebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb"
    ports:
      - "4000:80"
    networks:
      - bancoMongo