version: '3.4'

networks:
    backend:
    sql_server_network:

services:
  sqlserver:
    image : mcr.microsoft.com/mssql/server:2022-latest
    container_name : sqlserver
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Numsey#2021"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql3
    ports:
      - '11433:1433'
    networks:
      - sql_server_network

  ms.services.auth.webapi:
    image: msservicesauthwebapi
    container_name : msservicesauthwebapi
    build:
      context: .
      dockerfile: ./MS.Services.Auth.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:SqlConnection=Server=sqlserver;Database=AuthDb;User Id=sa;Password=Numsey#2021"
    depends_on:
      - sqlserver
    ports:
      - '4000:80'
    networks:
      - sql_server_network
      - backend