version: '3.4'

volumes:
  mssql:
networks:
    backend:
    sql_server_network:

services:
  sqlserver:
    restart: always
    image : mcr.microsoft.com/mssql/server:2022-latest
    container_name : sqlserver
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "Numsey#2021"
    volumes:
      - c:\dados\volumes\mssql:/var/opt/mssql/data
    ports:
      - 11433:1433
    networks:
      - 'backend'
